---
site:
  title: "Offline CLA for Red Hat Enterprise Linux"
  url: https://github.com/rhpds/zt-cla-on-prem
  start_page: modules::module-01.adoc

asciidoc:
  attributes:
    lab_name: "Offline CLA for Red Hat Enterprise Linux"
    release-version: master
    page-pagination: true

content:
  sources:
    - url: ./
      start_path: content
ui:
  bundle:
    url: https://github.com/rhpds/nookbag-bundle/releases/download/v0.0.3/ui-bundle.zip
    snapshot: true

output:
  dir: ./www/www

runtime:
  cache_dir: ./.cache/antora
