---
site:
  title: "Image Mode is the best mode"
  url: https://github.com/rhpds/zt-cla-on-prem
  start_page: modules::module-01.adoc

asciidoc:
  attributes:
    lab_name: "Image Mode is the best mode"
    release-version: master
    page-pagination: true

content:
  sources:
    - url: ./
      start_path: content
ui:
  bundle:
    url: https://github.com/rhpds/rhdp_showroom_theme/releases/download/rh-one-2025/ui-bundle.zip 
    snapshot: true

output:
  dir: ./www/www

runtime:
  cache_dir: ./.cache/antora
