=== Configure the command line assistant
Start the container using the `rhel-cla` command.
[source,bash,run]
----
rhel-cla start
----

Change the command line assistant configuration to use the local server. You can manually modify `/etc/xdg/command-line-assistant/config.toml` or use the following command.
[source,bash,run]
----
sed -i 's|https://cert.console.redhat.com/api/lightspeed/v1|http://127.0.0.1:8000/v1|g' /etc/xdg/command-line-assistant/config.toml
----

Because we are running this model on CPU only, we need to increase the timeout period from 30 seconds to 120 seconds.
[source,bash,run]
----
sed -i 's|timeout = 30|timeout = 120|g' /etc/xdg/command-line-assistant/config.toml
----

Restart clad using systemctl to reload the configuration.
[source,bash,run]
----
systemctl restart clad
----

[NOTE]
.Behavior of developer preview software may differ from that of the GA release
====
For this demo, we ran a command between the first and second steps of this lab (i.e., just before you ran `rhel-cla start`). We don't anticipate this command to be necessary in the GA release, so it is not included in the lab. however, if you wish to replicate this lab using the developer preview, you will need to run the following command prior to `rhel-cla start`
----
sed -i 's|quay.io/ramalama/ramalama:latest|quay.io/ramalama/ramalama:6ae863e9f552797b45d0fd8632c4f7ec9b78c430|g' ~/.config/rhel-cla/.env
----
====